#!/bin/bash
# LWO Installation Script

set -e

echo "=== Linux Workspace Observer Installation ==="
echo

# Detect shell type
SHELL_TYPE=""
if [ -n "$ZSH_VERSION" ]; then
    SHELL_TYPE="zsh"
    RC_FILE="$HOME/.zshrc"
elif [ -n "$BASH_VERSION" ]; then
    SHELL_TYPE="bash"
    RC_FILE="$HOME/.bashrc"
else
    echo "Error: Unsupported shell. LWO requires zsh or bash."
    exit 1
fi

echo "Detected shell: $SHELL_TYPE"
echo "RC file: $RC_FILE"
echo

# Create directories
echo "Creating LWO directories..."
mkdir -p "$HOME/.local/share/lwo"
mkdir -p "$HOME/.config/lwo"
mkdir -p "$HOME/lwo-reports"

# Copy config file if it doesn't exist
CONFIG_FILE="$HOME/.config/lwo/lwo.toml"
if [ ! -f "$CONFIG_FILE" ]; then
    echo "Creating default config file..."
    cp "$(dirname "$0")/../config/lwo.toml.example" "$CONFIG_FILE"
    echo "Config file created at: $CONFIG_FILE"
    echo "Please edit it to configure database and OpenAI API settings."
else
    echo "Config file already exists: $CONFIG_FILE"
fi

# Install shell hook
HOOK_FILE="$(dirname "$0")/shell_hooks/${SHELL_TYPE}_hook.sh"
if [ ! -f "$HOOK_FILE" ]; then
    echo "Error: Hook file not found: $HOOK_FILE"
    exit 1
fi

echo
echo "Installing shell hook to $RC_FILE..."

# Check if hook is already installed
if grep -q "# LWO Shell Hook" "$RC_FILE" 2>/dev/null; then
    echo "Shell hook already installed. Skipping..."
else
    echo "" >> "$RC_FILE"
    echo "# LWO Shell Hook - Auto-generated by LWO installer" >> "$RC_FILE"
    cat "$HOOK_FILE" >> "$RC_FILE"
    echo "Shell hook installed successfully."
fi

echo
echo "=== Installation Complete ==="
echo
echo "Next steps:"
echo "1. Edit config file: $CONFIG_FILE"
echo "   - Set database password: export LWO_DB_PASSWORD='your_password'"
echo "   - Set OpenAI API key: export OPENAI_API_KEY='sk-...'"
echo "2. Reload shell: source $RC_FILE"
echo "3. Start LWO daemon: uv run main.py start"
echo
echo "For more information, see README.md"
